--------------------------------------------------------------------------------
-- 02_tabelas_app.sql
--
-- Cria as tabelas APP_* no schema COMPRAS: tudo que a aplicação (dashboard)
-- escreve. O dbt nunca cria nem derruba nada com prefixo APP_ (CONTEXTO.md §2).
--
-- Idempotente: cada CREATE TABLE é precedido de uma checagem em USER_TABLES,
-- então rodar o script de novo não derruba dado nenhum. Evolução de schema
-- (nova coluna, novo índice) é ALTER separado, num script de migração à
-- parte — nunca editado aqui depois de publicado.
--
-- Colunas IDENTITY (APP_DECISAO_PRECO_HIST.ID_HIST, APP_USUARIO.ID_USUARIO,
-- APP_AUDITORIA.ID_AUDITORIA) usam GENERATED ALWAYS AS IDENTITY, de propósito
-- e não GENERATED BY DEFAULT: BY DEFAULT aceita um id explícito no INSERT sem
-- avançar a sequência interna, o que mais cedo ou mais tarde bate de frente
-- com um valor gerado depois e falha com ORA-00001. Se algum dia for preciso
-- restaurar um backup que exija gravar um id explícito (ex.: reimportar uma
-- linha de auditoria com o ID_AUDITORIA original), isso é feito de forma
-- explícita e temporária:
--   alter table app_auditoria modify id_auditoria generated by default as identity;
--   -- ... insere com id explícito ...
--   alter table app_auditoria modify id_auditoria generated always as identity;
-- Nunca deixar a tabela em BY DEFAULT como estado permanente.
--
-- Rodar conectado como COMPRAS.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1. APP_DECISAO_PRECO — decisão vigente de margem/preço por produto.
--
-- Uma linha só existe aqui quando existe decisão humana gravada para pelo
-- menos um dos campos. MARGEM_ALVO e MARGEM_ALVO_VAREJO são NULLABLE e SEM
-- DEFAULT de propósito: NULL significa "sem decisão de margem registrada" e
-- é o dbt (fora desta tabela) que aplica o padrão de negócio de 20%
-- (CONTEXTO.md §6 regra 10). Um DEFAULT 0.20 NOT NULL aqui seria uma mentira
-- silenciosa: um INSERT que só grava preço gravaria margem 0,20 junto, e essa
-- margem ficaria indistinguível de uma decisão humana de fato.
--------------------------------------------------------------------------------
declare
    v_existe number;
begin
    select count(*) into v_existe from user_tables where table_name = 'APP_DECISAO_PRECO';
    if v_existe = 0 then
        execute immediate q'[
            create table app_decisao_preco (
                id_produto           number(10)      not null,
                margem_alvo          number(9,6),
                margem_alvo_varejo   number(9,6),
                alt_pv_at_av         number(14,4),
                alt_pv_var_av        number(14,4),
                atualizado_em        timestamp        default systimestamp not null,
                atualizado_por       varchar2(60)     not null,
                constraint pk_app_decisao_preco primary key (id_produto),
                constraint ck_app_decisao_preco_ma
                    check (margem_alvo between -1 and 1),
                constraint ck_app_decisao_preco_mav
                    check (margem_alvo_varejo between -1 and 1),
                constraint ck_app_decisao_preco_pv
                    check (alt_pv_at_av > 0),
                constraint ck_app_decisao_preco_pvv
                    check (alt_pv_var_av > 0)
            )
        ]';
    end if;
end;
/

comment on table app_decisao_preco is
    'Decisão vigente de margem e preço final por produto. Uma linha por SKU com pelo menos um campo decidido; SKU sem linha, ou com MARGEM_ALVO/MARGEM_ALVO_VAREJO NULL, usa o padrão de negócio (margem 20%) aplicado pelo dbt fora desta tabela. Toda alteração aqui deve gravar o valor anterior em APP_DECISAO_PRECO_HIST antes de sobrescrever.';
comment on column app_decisao_preco.id_produto is
    'CODPROD do CEDEP (cedep.pcprodut.codprod). Não há FK física para CEDEP: a fronteira do projeto proíbe qualquer dependência de schema cruzando para lá (CONTEXTO.md §2).';
comment on column app_decisao_preco.margem_alvo is
    'Margem alvo decidida para o atacado, fração decimal (0.20 = 20%; CHECK entre -1 e 1 — quem digitar "20" achando que é 20% recebe erro em vez de gravar 2000%). NULL = sem decisão humana registrada; o padrão de 20% (CONTEXTO.md §6 regra 10) é aplicado pelo dbt fora desta tabela, nunca gravado aqui como default.';
comment on column app_decisao_preco.margem_alvo_varejo is
    'Margem alvo decidida para o varejo (filiais fora de 02/09), fração decimal, mesma semântica de NULL e mesmo CHECK entre -1 e 1 de MARGEM_ALVO.';
comment on column app_decisao_preco.alt_pv_at_av is
    'Preço de venda final decidido para o atacado (ALT_PV_AT_AV). CHECK > 0 quando não nulo. NULL = ainda sem decisão humana registrada para este campo; nunca é preenchido automaticamente com uma sugestão do modelo (CONTEXTO.md §6 regra 10).';
comment on column app_decisao_preco.alt_pv_var_av is
    'Preço de venda final decidido para o varejo (ALT_PV_VAR_AV). CHECK > 0 quando não nulo. Mesma semântica de NULL que ALT_PV_AT_AV.';
comment on column app_decisao_preco.atualizado_em is
    'Timestamp da última gravação desta linha (não da criação).';
comment on column app_decisao_preco.atualizado_por is
    'Login (APP_USUARIO.login) de quem gravou o valor vigente.';

--------------------------------------------------------------------------------
-- 2. APP_DECISAO_PRECO_HIST — todo valor anterior de APP_DECISAO_PRECO.
--
-- Antes de sobrescrever uma linha em APP_DECISAO_PRECO, a aplicação grava o
-- valor que está saindo aqui. DECIDIDO_EM é o instante desse arquivamento
-- (quando o valor deixou de valer), não o instante em que ele foi criado —
-- esse já está em ATUALIZADO_EM, copiado da linha original. MARGEM_ALVO e
-- MARGEM_ALVO_VAREJO são NULLABLE aqui pela mesma razão que em
-- APP_DECISAO_PRECO: uma linha arquivada pode ter sido gravada só com preço,
-- sem margem decidida, e o histórico precisa preservar esse NULL, não
-- inventar um valor.
--------------------------------------------------------------------------------
declare
    v_existe number;
begin
    select count(*) into v_existe from user_tables where table_name = 'APP_DECISAO_PRECO_HIST';
    if v_existe = 0 then
        execute immediate q'[
            create table app_decisao_preco_hist (
                id_hist              number         generated always as identity,
                id_produto           number(10)      not null,
                margem_alvo          number(9,6),
                margem_alvo_varejo   number(9,6),
                alt_pv_at_av         number(14,4),
                alt_pv_var_av        number(14,4),
                atualizado_em        timestamp        not null,
                atualizado_por       varchar2(60)     not null,
                decidido_em          timestamp        default systimestamp not null,
                constraint pk_app_decisao_preco_hist primary key (id_hist),
                constraint ck_app_decisao_preco_h_ma
                    check (margem_alvo between -1 and 1),
                constraint ck_app_decisao_preco_h_mav
                    check (margem_alvo_varejo between -1 and 1),
                constraint ck_app_decisao_preco_h_pv
                    check (alt_pv_at_av > 0),
                constraint ck_app_decisao_preco_h_pvv
                    check (alt_pv_var_av > 0)
            )
        ]';
    end if;
end;
/

declare
    v_existe number;
begin
    select count(*) into v_existe from user_indexes where index_name = 'IX_APP_DECISAO_PRECO_HIST_PRD';
    if v_existe = 0 then
        execute immediate
            'create index ix_app_decisao_preco_hist_prd on app_decisao_preco_hist (id_produto)';
    end if;
end;
/

comment on table app_decisao_preco_hist is
    'Histórico de todo valor anterior de APP_DECISAO_PRECO. Uma linha é inserida aqui a cada vez que uma linha de APP_DECISAO_PRECO é sobrescrita, com o conteúdo que estava saindo. Nunca é alterada nem apagada pela aplicação — só cresce.';
comment on column app_decisao_preco_hist.id_hist is
    'Chave técnica sequencial (IDENTITY, GENERATED ALWAYS — nunca aceita id explícito em uso normal), sem significado de negócio.';
comment on column app_decisao_preco_hist.id_produto is
    'CODPROD do CEDEP a que este valor histórico se refere. Indexado (IX_APP_DECISAO_PRECO_HIST_PRD) para consultar o histórico de um produto.';
comment on column app_decisao_preco_hist.margem_alvo is
    'Margem alvo do atacado que estava vigente antes desta substituição. NULL = a linha arquivada não tinha margem de atacado decidida (mesma semântica de APP_DECISAO_PRECO.margem_alvo). CHECK entre -1 e 1.';
comment on column app_decisao_preco_hist.margem_alvo_varejo is
    'Margem alvo do varejo que estava vigente antes desta substituição. NULL = a linha arquivada não tinha margem de varejo decidida. CHECK entre -1 e 1.';
comment on column app_decisao_preco_hist.alt_pv_at_av is
    'Preço final de atacado que estava vigente antes desta substituição (pode ser NULL, mesma semântica de APP_DECISAO_PRECO.alt_pv_at_av). CHECK > 0 quando não nulo.';
comment on column app_decisao_preco_hist.alt_pv_var_av is
    'Preço final de varejo que estava vigente antes desta substituição (pode ser NULL). CHECK > 0 quando não nulo.';
comment on column app_decisao_preco_hist.atualizado_em is
    'ATUALIZADO_EM original, copiado da linha de APP_DECISAO_PRECO no momento em que ela foi substituída — quando aquele valor passou a valer, não quando foi arquivado.';
comment on column app_decisao_preco_hist.atualizado_por is
    'ATUALIZADO_POR original, copiado da linha de APP_DECISAO_PRECO no momento da substituição.';
comment on column app_decisao_preco_hist.decidido_em is
    'Instante em que este valor deixou de ser o vigente (foi arquivado aqui por uma nova decisão).';

--------------------------------------------------------------------------------
-- 3. APP_DECISAO_PEDIDO — quantidade de pedido decidida por produto.
--
-- PEDIDO é digitado pelo comprador na UNIDADE DE EXIBIÇÃO do produto — a
-- mesma unidade mostrada na tela, equivalente à coluna BA (PEDIDO) da
-- planilha original. Essa unidade não é fixa: na planilha,
-- PEDIDO_UNIDADES (coluna BB) = PEDIDO x FATOR_EXIBICAO, e FATOR_EXIBICAO
-- (coluna K) é IF(dFornecedor.PEDIDO_EM='MASTER', EMBAL_COMPRA, 1) — um valor
-- que não mora nesta tabela e que muda quando o cadastro do fornecedor ou do
-- produto muda (CONTEXTO.md §6 regra 6). Se só guardássemos PEDIDO, uma
-- mudança de cadastro depois da gravação mudaria retroativamente o
-- significado da mesma linha, sem que ninguém a tivesse tocado. Por isso a
-- tabela também guarda FATOR_EXIBICAO: o fator vigente no INSTANTE da
-- decisão, congelado de propósito. A quantidade em unidades sempre se
-- recalcula a partir desta linha (PEDIDO x FATOR_EXIBICAO), nunca lendo o
-- fator do cadastro atual.
--------------------------------------------------------------------------------
declare
    v_existe number;
begin
    select count(*) into v_existe from user_tables where table_name = 'APP_DECISAO_PEDIDO';
    if v_existe = 0 then
        execute immediate q'[
            create table app_decisao_pedido (
                id_produto      number(10)      not null,
                pedido          number(14,4)     not null,
                fator_exibicao  number(14,6)     not null,
                atualizado_em   timestamp        default systimestamp not null,
                atualizado_por  varchar2(60)     not null,
                constraint pk_app_decisao_pedido primary key (id_produto),
                constraint ck_app_decisao_pedido_ped
                    check (pedido >= 0),
                constraint ck_app_decisao_pedido_fat
                    check (fator_exibicao > 0)
            )
        ]';
    end if;
end;
/

comment on table app_decisao_pedido is
    'Quantidade de pedido de compra decidida por produto. Uma linha por SKU com pedido gravado manualmente; SKU sem linha significa "sem pedido decidido ainda" e o dbt usa a sugestão calculada em fat_pedido. PEDIDO está na UNIDADE DE EXIBIÇÃO (equivalente à coluna BA da planilha), não na unidade de estoque; a quantidade em unidades = PEDIDO x FATOR_EXIBICAO, onde FATOR_EXIBICAO é o fator (dFornecedor.PEDIDO_EM / EMBAL_COMPRA — CONTEXTO.md §6 regra 6) vigente no instante em que esta linha foi gravada, congelado de propósito: ele vive fora desta tabela, no cadastro, e pode mudar depois — recalculá-lo no presente mudaria o significado de uma decisão já tomada.';
comment on column app_decisao_pedido.id_produto is
    'CODPROD do CEDEP (cedep.pcprodut.codprod). Sem FK física para o CEDEP (fronteira do projeto).';
comment on column app_decisao_pedido.pedido is
    'Quantidade de pedido decidida pelo comprador, EXATAMENTE como digitada, na unidade de exibição (coluna BA da planilha) — não é a unidade de estoque/unidades. CHECK >= 0. Para a quantidade em unidades, multiplicar por FATOR_EXIBICAO desta mesma linha (nunca pelo fator atual do cadastro).';
comment on column app_decisao_pedido.fator_exibicao is
    'Snapshot do fator de conversão vigente no instante da gravação (equivalente à coluna K/FATOR_EXIBICAO da planilha: EMBAL_COMPRA quando dFornecedor.PEDIDO_EM=MASTER, senão 1). CHECK > 0. Congelado de propósito: PEDIDO_UNIDADES desta linha = PEDIDO x FATOR_EXIBICAO, os dois sempre lidos juntos desta mesma linha, nunca recalculando a partir do cadastro atual — que pode ter mudado depois desta decisão.';
comment on column app_decisao_pedido.atualizado_em is
    'Timestamp da última gravação desta linha.';
comment on column app_decisao_pedido.atualizado_por is
    'Login (APP_USUARIO.login) de quem gravou o pedido vigente.';

--------------------------------------------------------------------------------
-- 4. APP_USUARIO — contas do dashboard.
--
-- Modelo espelha core/db_app.py + core/auth.py do app_relatorios (SQLite lá,
-- Oracle aqui): senha em bcrypt, troca obrigatória no primeiro acesso via
-- SENHA_PROVISORIA, desativar usuário (ATIVO=0) precisa derrubar sessões
-- abertas — isso é feito pela aplicação (DELETE em APP_SESSAO), não por
-- trigger, para manter a lógica de negócio em Python e auditável em
-- APP_AUDITORIA.
--------------------------------------------------------------------------------
declare
    v_existe number;
begin
    select count(*) into v_existe from user_tables where table_name = 'APP_USUARIO';
    if v_existe = 0 then
        execute immediate q'[
            create table app_usuario (
                id_usuario       number           generated always as identity,
                login            varchar2(60)     not null,
                nome             varchar2(120)    not null,
                email            varchar2(120),
                senha_hash       varchar2(100),
                origem           varchar2(10)     default 'local' not null,
                senha_provisoria number(1)        default 1 not null,
                ativo            number(1)        default 1 not null,
                eh_admin         number(1)        default 0 not null,
                eh_diretoria     number(1)        default 0 not null,
                criado_em        timestamp        default systimestamp not null,
                ultimo_acesso    timestamp,
                constraint pk_app_usuario primary key (id_usuario),
                constraint uq_app_usuario_login unique (login),
                constraint ck_app_usuario_origem check (origem in ('local', 'ad')),
                constraint ck_app_usuario_prov check (senha_provisoria in (0, 1)),
                constraint ck_app_usuario_ativo check (ativo in (0, 1)),
                constraint ck_app_usuario_admin check (eh_admin in (0, 1)),
                constraint ck_app_usuario_diret check (eh_diretoria in (0, 1))
            )
        ]';
    end if;
end;
/

comment on table app_usuario is
    'Contas do dashboard de compras. Login local por enquanto (ORIGEM=local); ORIGEM=ad é o ponto de entrada já previsto para login de domínio, sem mudar o resto do modelo (mesmo desenho de core/auth.py do app_relatorios).';
comment on column app_usuario.id_usuario is
    'Chave técnica sequencial (IDENTITY, GENERATED ALWAYS — nunca aceita id explícito em uso normal).';
comment on column app_usuario.login is
    'Identificador de acesso, único, case-sensitive no Oracle (comparar em minúsculas na aplicação se precisar de case-insensitive).';
comment on column app_usuario.nome is
    'Nome de exibição do usuário.';
comment on column app_usuario.email is
    'E-mail de contato, opcional.';
comment on column app_usuario.senha_hash is
    'Hash bcrypt da senha (nunca a senha em texto). NULL só é aceitável para uma conta ainda não provisionada com senha, se esse fluxo existir.';
comment on column app_usuario.origem is
    'local = senha própria conferida aqui; ad = login de domínio (autenticação delegada), ainda não implementado.';
comment on column app_usuario.senha_provisoria is
    '1 = senha foi definida pelo admin e o usuário é obrigado a trocá-la no próximo login; 0 = senha já é escolha do próprio usuário.';
comment on column app_usuario.ativo is
    '0 = conta desativada. Contas não são excluídas, só desativadas (ver comentário de APP_SESSAO.id_usuario sobre o porquê). Desativar deve ser acompanhado, pela aplicação, do DELETE das linhas do usuário em APP_SESSAO (derruba sessões abertas na hora).';
comment on column app_usuario.eh_admin is
    '1 = pode administrar usuários e configuração do dashboard.';
comment on column app_usuario.eh_diretoria is
    '1 = enxerga todo o catálogo sem restrição de escopo (quando um controle de escopo por dimensão existir).';
comment on column app_usuario.criado_em is
    'Timestamp de criação da conta.';
comment on column app_usuario.ultimo_acesso is
    'Timestamp do último login bem-sucedido.';

--------------------------------------------------------------------------------
-- 5. APP_SESSAO — sessões ativas (token opaco, não cookie assinado).
--
-- Token opaco e aleatório, gerado e conferido pela aplicação (não pelo
-- banco): permite que desativar um usuário derrube a sessão dele
-- imediatamente, o que um cookie auto-contido só faria esperando expirar
-- (mesmo raciocínio de core/auth.py do app_relatorios).
--------------------------------------------------------------------------------
declare
    v_existe number;
begin
    select count(*) into v_existe from user_tables where table_name = 'APP_SESSAO';
    if v_existe = 0 then
        execute immediate q'[
            create table app_sessao (
                token       varchar2(64)    not null,
                id_usuario  number          not null,
                criado_em   timestamp       default systimestamp not null,
                expira_em   timestamp       not null,
                ip          varchar2(45),
                constraint pk_app_sessao primary key (token),
                constraint fk_app_sessao_usuario foreign key (id_usuario)
                    references app_usuario (id_usuario) on delete cascade
            )
        ]';
    end if;
end;
/

declare
    v_existe number;
begin
    select count(*) into v_existe from user_indexes where index_name = 'IX_APP_SESSAO_USUARIO';
    if v_existe = 0 then
        execute immediate
            'create index ix_app_sessao_usuario on app_sessao (id_usuario)';
    end if;
end;
/

comment on table app_sessao is
    'Sessões de login ativas. Token opaco (gerado com secrets.token_urlsafe na aplicação), não JWT/cookie assinado. Linha apagada = sessão encerrada (logout, expiração limpa por rotina, ou usuário desativado).';
comment on column app_sessao.token is
    'Token de sessão, opaco e aleatório. É a própria chave primária: procurar por token é O(1) e não exige decodificar nada.';
comment on column app_sessao.id_usuario is
    'FK para APP_USUARIO. Na prática, uma conta de usuário não é excluída — só desativada (ATIVO=0): a FK sem cascade de APP_AUDITORIA.id_usuario já impede excluir um usuário que tenha gerado alguma linha de auditoria, e toda conta relevante gera. É a aplicação, não o banco, que apaga as sessões da conta no momento em que ela é desativada (DELETE em APP_SESSAO, ver comentário de APP_USUARIO.ativo). O ON DELETE CASCADE aqui é só uma salvaguarda para o caso raro de uma conta sem nenhuma auditoria ser excluída de fato — não é o caminho normal de desativação.';
comment on column app_sessao.criado_em is
    'Timestamp de abertura da sessão (login).';
comment on column app_sessao.expira_em is
    'Timestamp de expiração. A aplicação recusa token com EXPIRA_EM no passado, mesmo antes de uma rotina de limpeza apagar a linha.';
comment on column app_sessao.ip is
    'IP de origem do login, para auditoria/diagnóstico.';

--------------------------------------------------------------------------------
-- 6. APP_AUDITORIA — trilha de quem fez o quê.
--
-- Cobre tanto ações de autenticação (login, logout, troca de senha,
-- desativação) quanto gravações de negócio (decisão de preço, decisão de
-- pedido), usando TABELA_REFERENCIA/CHAVE_REFERENCIA para apontar o que foi
-- afetado sem precisar de uma tabela de auditoria por entidade.
--------------------------------------------------------------------------------
declare
    v_existe number;
begin
    select count(*) into v_existe from user_tables where table_name = 'APP_AUDITORIA';
    if v_existe = 0 then
        execute immediate q'[
            create table app_auditoria (
                id_auditoria       number          generated always as identity,
                id_usuario         number,
                acao               varchar2(60)    not null,
                tabela_referencia  varchar2(30),
                chave_referencia   varchar2(60),
                detalhe            clob,
                criado_em          timestamp       default systimestamp not null,
                ip                 varchar2(45),
                constraint pk_app_auditoria primary key (id_auditoria),
                constraint fk_app_auditoria_usuario foreign key (id_usuario)
                    references app_usuario (id_usuario)
            )
        ]';
    end if;
end;
/

declare
    v_existe number;
begin
    select count(*) into v_existe from user_indexes where index_name = 'IX_APP_AUDITORIA_USUARIO';
    if v_existe = 0 then
        execute immediate
            'create index ix_app_auditoria_usuario on app_auditoria (id_usuario, criado_em)';
    end if;
end;
/

declare
    v_existe number;
begin
    select count(*) into v_existe from user_indexes where index_name = 'IX_APP_AUDITORIA_REF';
    if v_existe = 0 then
        execute immediate
            'create index ix_app_auditoria_ref on app_auditoria (tabela_referencia, chave_referencia)';
    end if;
end;
/

comment on table app_auditoria is
    'Trilha de auditoria de toda ação relevante do dashboard: login/logout, troca de senha, ativação/desativação de conta, e toda gravação de negócio (decisão de preço, decisão de pedido). Só cresce; a aplicação nunca faz UPDATE nem DELETE aqui.';
comment on column app_auditoria.id_auditoria is
    'Chave técnica sequencial (IDENTITY, GENERATED ALWAYS — nunca aceita id explícito em uso normal).';
comment on column app_auditoria.id_usuario is
    'Quem executou a ação. NULL para ação de sistema sem usuário associado (ex.: rotina de limpeza de sessão vencida). Sem ON DELETE CASCADE de propósito: excluir um usuário não deve apagar o rastro do que ele fez — e, na prática, essa mesma FK é o que impede excluir um usuário que já agiu (ver comentário de APP_SESSAO.id_usuario).';
comment on column app_auditoria.acao is
    'Identificador curto da ação, ex.: LOGIN, LOGOUT, TROCA_SENHA, DESATIVAR_USUARIO, GRAVAR_DECISAO_PRECO, GRAVAR_DECISAO_PEDIDO.';
comment on column app_auditoria.tabela_referencia is
    'Tabela de negócio afetada pela ação, quando houver (ex.: APP_DECISAO_PRECO). NULL para ações sem tabela associada (ex.: LOGIN).';
comment on column app_auditoria.chave_referencia is
    'Chave do registro afetado em TABELA_REFERENCIA, como texto (ex.: o ID_PRODUTO). NULL quando não se aplica.';
comment on column app_auditoria.detalhe is
    'Detalhe livre da ação (ex.: valor anterior/novo em JSON), CLOB e não VARCHAR2 de propósito: em AL32UTF8 o limite de VARCHAR2 é em bytes, e um JSON com acentuação pode estourar 4.000 bytes bem antes de 4.000 caracteres (ORA-12899) — o que, numa gravação de auditoria feita na mesma transação da decisão de negócio, derrubaria a decisão junto. Sem estrutura fixa de propósito: o formato é decisão da aplicação, não do schema.';
comment on column app_auditoria.criado_em is
    'Timestamp da ação.';
comment on column app_auditoria.ip is
    'IP de origem da requisição que gerou a ação, quando aplicável.';
