--------------------------------------------------------------------------------
-- 02_tabelas_auth.sql
--
-- Cria as tabelas de autenticação/auditoria do dashboard no schema COMPRAS:
-- APP_USUARIO, APP_SESSAO, APP_AUDITORIA. O dbt nunca cria nem derruba nada
-- com prefixo APP_ (CONTEXTO.md §2).
--
-- Idempotente: cada CREATE TABLE é precedido de uma checagem em USER_TABLES,
-- então rodar o script de novo não derruba dado nenhum. Evolução de schema
-- (nova coluna, novo índice) é ALTER separado, num script de migração à
-- parte — nunca editado aqui depois de publicado.
--
-- Colunas IDENTITY (APP_USUARIO.ID_USUARIO, APP_AUDITORIA.ID_AUDITORIA) usam
-- GENERATED ALWAYS AS IDENTITY, de propósito e não GENERATED BY DEFAULT: BY
-- DEFAULT aceita um id explícito no INSERT sem avançar a sequência interna,
-- o que mais cedo ou mais tarde bate de frente com um valor gerado depois e
-- falha com ORA-00001. Se algum dia for preciso restaurar um backup que
-- exija gravar um id explícito (ex.: reimportar uma linha de auditoria com o
-- ID_AUDITORIA original), isso é feito de forma explícita e temporária:
--   alter table app_auditoria modify id_auditoria generated by default as identity;
--   -- ... insere com id explícito ...
--   alter table app_auditoria modify id_auditoria generated always as identity;
-- Nunca deixar a tabela em BY DEFAULT como estado permanente.
--
-- Rodar conectado como COMPRAS.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1. APP_USUARIO — contas do dashboard.
--
-- Modelo espelha core/db_app.py + core/auth.py do app_relatorios (SQLite lá,
-- Oracle aqui): senha em bcrypt, troca obrigatória no primeiro acesso via
-- SENHA_PROVISORIA, desativar usuário (ATIVO=0) precisa derrubar sessões
-- abertas — isso é feito pela aplicação (DELETE em APP_SESSAO), não por
-- trigger, para manter a lógica de negócio em Python e auditável em
-- APP_AUDITORIA.
--------------------------------------------------------------------------------
declare
    v_existe number;
begin
    select count(*) into v_existe from user_tables where table_name = 'APP_USUARIO';
    if v_existe = 0 then
        execute immediate q'[
            create table app_usuario (
                id_usuario       number           generated always as identity,
                login            varchar2(60)     not null,
                nome             varchar2(120)    not null,
                email            varchar2(120),
                senha_hash       varchar2(100),
                origem           varchar2(10)     default 'local' not null,
                senha_provisoria number(1)        default 1 not null,
                ativo            number(1)        default 1 not null,
                eh_admin         number(1)        default 0 not null,
                eh_diretoria     number(1)        default 0 not null,
                criado_em        timestamp        default systimestamp not null,
                ultimo_acesso    timestamp,
                constraint pk_app_usuario primary key (id_usuario),
                constraint uq_app_usuario_login unique (login),
                constraint ck_app_usuario_origem check (origem in ('local', 'ad')),
                constraint ck_app_usuario_prov check (senha_provisoria in (0, 1)),
                constraint ck_app_usuario_ativo check (ativo in (0, 1)),
                constraint ck_app_usuario_admin check (eh_admin in (0, 1)),
                constraint ck_app_usuario_diret check (eh_diretoria in (0, 1))
            )
        ]';
    end if;
end;
/

comment on table app_usuario is
    'Contas do dashboard de compras. Login local por enquanto (ORIGEM=local); ORIGEM=ad é o ponto de entrada já previsto para login de domínio, sem mudar o resto do modelo (mesmo desenho de core/auth.py do app_relatorios).';
comment on column app_usuario.id_usuario is
    'Chave técnica sequencial (IDENTITY, GENERATED ALWAYS — nunca aceita id explícito em uso normal).';
comment on column app_usuario.login is
    'Identificador de acesso, único, case-sensitive no Oracle (comparar em minúsculas na aplicação se precisar de case-insensitive).';
comment on column app_usuario.nome is
    'Nome de exibição do usuário.';
comment on column app_usuario.email is
    'E-mail de contato, opcional.';
comment on column app_usuario.senha_hash is
    'Hash bcrypt da senha (nunca a senha em texto). NULL só é aceitável para uma conta ainda não provisionada com senha, se esse fluxo existir.';
comment on column app_usuario.origem is
    'local = senha própria conferida aqui; ad = login de domínio (autenticação delegada), ainda não implementado.';
comment on column app_usuario.senha_provisoria is
    '1 = senha foi definida pelo admin e o usuário é obrigado a trocá-la no próximo login; 0 = senha já é escolha do próprio usuário.';
comment on column app_usuario.ativo is
    '0 = conta desativada. Contas não são excluídas, só desativadas (ver comentário de APP_SESSAO.id_usuario sobre o porquê). Desativar deve ser acompanhado, pela aplicação, do DELETE das linhas do usuário em APP_SESSAO (derruba sessões abertas na hora).';
comment on column app_usuario.eh_admin is
    '1 = pode administrar usuários e configuração do dashboard.';
comment on column app_usuario.eh_diretoria is
    '1 = enxerga todo o catálogo sem restrição de escopo (quando um controle de escopo por dimensão existir).';
comment on column app_usuario.criado_em is
    'Timestamp de criação da conta.';
comment on column app_usuario.ultimo_acesso is
    'Timestamp do último login bem-sucedido.';

--------------------------------------------------------------------------------
-- 2. APP_SESSAO — sessões ativas (token opaco, não cookie assinado).
--
-- Token opaco e aleatório, gerado e conferido pela aplicação (não pelo
-- banco): permite que desativar um usuário derrube a sessão dele
-- imediatamente, o que um cookie auto-contido só faria esperando expirar
-- (mesmo raciocínio de core/auth.py do app_relatorios).
--------------------------------------------------------------------------------
declare
    v_existe number;
begin
    select count(*) into v_existe from user_tables where table_name = 'APP_SESSAO';
    if v_existe = 0 then
        execute immediate q'[
            create table app_sessao (
                token       varchar2(64)    not null,
                id_usuario  number          not null,
                criado_em   timestamp       default systimestamp not null,
                expira_em   timestamp       not null,
                ip          varchar2(45),
                constraint pk_app_sessao primary key (token),
                constraint fk_app_sessao_usuario foreign key (id_usuario)
                    references app_usuario (id_usuario) on delete cascade
            )
        ]';
    end if;
end;
/

declare
    v_existe number;
begin
    select count(*) into v_existe from user_indexes where index_name = 'IX_APP_SESSAO_USUARIO';
    if v_existe = 0 then
        execute immediate
            'create index ix_app_sessao_usuario on app_sessao (id_usuario)';
    end if;
end;
/

comment on table app_sessao is
    'Sessões de login ativas. Token opaco (gerado com secrets.token_urlsafe na aplicação), não JWT/cookie assinado. Linha apagada = sessão encerrada (logout, expiração limpa por rotina, ou usuário desativado).';
comment on column app_sessao.token is
    'Token de sessão, opaco e aleatório. É a própria chave primária: procurar por token é O(1) e não exige decodificar nada.';
comment on column app_sessao.id_usuario is
    'FK para APP_USUARIO. Na prática, uma conta de usuário não é excluída — só desativada (ATIVO=0): a FK sem cascade de APP_AUDITORIA.id_usuario já impede excluir um usuário que tenha gerado alguma linha de auditoria, e toda conta relevante gera. É a aplicação, não o banco, que apaga as sessões da conta no momento em que ela é desativada (DELETE em APP_SESSAO, ver comentário de APP_USUARIO.ativo). O ON DELETE CASCADE aqui é só uma salvaguarda para o caso raro de uma conta sem nenhuma auditoria ser excluída de fato — não é o caminho normal de desativação.';
comment on column app_sessao.criado_em is
    'Timestamp de abertura da sessão (login).';
comment on column app_sessao.expira_em is
    'Timestamp de expiração. A aplicação recusa token com EXPIRA_EM no passado, mesmo antes de uma rotina de limpeza apagar a linha.';
comment on column app_sessao.ip is
    'IP de origem do login, para auditoria/diagnóstico.';

--------------------------------------------------------------------------------
-- 3. APP_AUDITORIA — trilha de quem fez o quê.
--
-- Cobre tanto ações de autenticação (login, logout, troca de senha,
-- desativação) quanto gravações de negócio (decisão de preço, decisão de
-- pedido), usando TABELA_REFERENCIA/CHAVE_REFERENCIA para apontar o que foi
-- afetado sem precisar de uma tabela de auditoria por entidade.
--------------------------------------------------------------------------------
declare
    v_existe number;
begin
    select count(*) into v_existe from user_tables where table_name = 'APP_AUDITORIA';
    if v_existe = 0 then
        execute immediate q'[
            create table app_auditoria (
                id_auditoria       number          generated always as identity,
                id_usuario         number,
                acao               varchar2(60)    not null,
                tabela_referencia  varchar2(30),
                chave_referencia   varchar2(60),
                detalhe            clob,
                criado_em          timestamp       default systimestamp not null,
                ip                 varchar2(45),
                constraint pk_app_auditoria primary key (id_auditoria),
                constraint fk_app_auditoria_usuario foreign key (id_usuario)
                    references app_usuario (id_usuario)
            )
        ]';
    end if;
end;
/

declare
    v_existe number;
begin
    select count(*) into v_existe from user_indexes where index_name = 'IX_APP_AUDITORIA_USUARIO';
    if v_existe = 0 then
        execute immediate
            'create index ix_app_auditoria_usuario on app_auditoria (id_usuario, criado_em)';
    end if;
end;
/

declare
    v_existe number;
begin
    select count(*) into v_existe from user_indexes where index_name = 'IX_APP_AUDITORIA_REF';
    if v_existe = 0 then
        execute immediate
            'create index ix_app_auditoria_ref on app_auditoria (tabela_referencia, chave_referencia)';
    end if;
end;
/

comment on table app_auditoria is
    'Trilha de auditoria de toda ação relevante do dashboard: login/logout, troca de senha, ativação/desativação de conta, e toda gravação de negócio (decisão de preço, decisão de pedido). Só cresce; a aplicação nunca faz UPDATE nem DELETE aqui.';
comment on column app_auditoria.id_auditoria is
    'Chave técnica sequencial (IDENTITY, GENERATED ALWAYS — nunca aceita id explícito em uso normal).';
comment on column app_auditoria.id_usuario is
    'Quem executou a ação. NULL para ação de sistema sem usuário associado (ex.: rotina de limpeza de sessão vencida). Sem ON DELETE CASCADE de propósito: excluir um usuário não deve apagar o rastro do que ele fez — e, na prática, essa mesma FK é o que impede excluir um usuário que já agiu (ver comentário de APP_SESSAO.id_usuario).';
comment on column app_auditoria.acao is
    'Identificador curto da ação, ex.: LOGIN, LOGOUT, TROCA_SENHA, DESATIVAR_USUARIO, GRAVAR_DECISAO_PRECO, GRAVAR_DECISAO_PEDIDO.';
comment on column app_auditoria.tabela_referencia is
    'Tabela de negócio afetada pela ação, quando houver (ex.: APP_DECISAO_PRECO). NULL para ações sem tabela associada (ex.: LOGIN).';
comment on column app_auditoria.chave_referencia is
    'Chave do registro afetado em TABELA_REFERENCIA, como texto (ex.: o ID_PRODUTO). NULL quando não se aplica.';
comment on column app_auditoria.detalhe is
    'Detalhe livre da ação (ex.: valor anterior/novo em JSON), CLOB e não VARCHAR2 de propósito: em AL32UTF8 o limite de VARCHAR2 é em bytes, e um JSON com acentuação pode estourar 4.000 bytes bem antes de 4.000 caracteres (ORA-12899) — o que, numa gravação de auditoria feita na mesma transação da decisão de negócio, derrubaria a decisão junto. Sem estrutura fixa de propósito: o formato é decisão da aplicação, não do schema.';
comment on column app_auditoria.criado_em is
    'Timestamp da ação.';
comment on column app_auditoria.ip is
    'IP de origem da requisição que gerou a ação, quando aplicável.';
