--------------------------------------------------------------------------------
-- 03_tabelas_decisao.sql
--
-- Cria APP_DECISAO_PRECO e APP_DECISAO_PRECO_HIST no schema COMPRAS: decisão
-- vigente de margem/preço por produto e o histórico de todo valor anterior.
-- O dbt nunca cria nem derruba nada com prefixo APP_ (CONTEXTO.md §2).
--
-- Etapa 14: APP_DECISAO_PRECO_HIST tinha 0 linhas apesar de 34 gravações
-- auditadas (GRAVAR_DECISAO_PRECO) — medido antes de decidir manter ou não.
-- Conferido em 12/09/2026: o mecanismo de arquivamento funciona (a segunda
-- gravação sobre o mesmo produto, sem limpeza no meio, popula corretamente
-- o "anterior" antes de sobrescrever — produto 3446, eventos de auditoria
-- 554→558, 11/09 08:20:06). O zero de hoje é explicado por dois fatores
-- somados, nenhum deles defeito deste schema: (1) os scripts de
-- validar/validar_lote_preco.py e validar/validar_ordenacao_paginada.py
-- fazem DELETE em APP_DECISAO_PRECO_HIST e APP_DECISAO_PRECO como
-- setup/limpeza dos próprios testes, e (2) as 4 linhas que sobrevivem em
-- produção hoje (produtos 9, 6871, 7973, 8817) são todas primeira gravação
-- daquele produto — sem valor anterior, não há o que arquivar. Tabela fica:
-- carrega peso morto seria um mecanismo que não funciona, não um mecanismo
-- correto que ainda não teve caso.
--
-- Idempotente: cada CREATE TABLE é precedido de uma checagem em USER_TABLES,
-- então rodar o script de novo não derruba dado nenhum. Evolução de schema
-- (nova coluna, novo índice) é ALTER separado, num script de migração à
-- parte — nunca editado aqui depois de publicado.
--
-- APP_DECISAO_PRECO_HIST.ID_HIST usa GENERATED ALWAYS AS IDENTITY, de
-- propósito e não GENERATED BY DEFAULT: BY DEFAULT aceita um id explícito no
-- INSERT sem avançar a sequência interna, o que mais cedo ou mais tarde bate
-- de frente com um valor gerado depois e falha com ORA-00001. Se algum dia
-- for preciso restaurar um backup que exija gravar um id explícito, isso é
-- feito de forma explícita e temporária:
--   alter table app_decisao_preco_hist modify id_hist generated by default as identity;
--   -- ... insere com id explícito ...
--   alter table app_decisao_preco_hist modify id_hist generated always as identity;
-- Nunca deixar a tabela em BY DEFAULT como estado permanente.
--
-- Rodar conectado como COMPRAS.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1. APP_DECISAO_PRECO — decisão vigente de margem/preço por produto.
--
-- Uma linha só existe aqui quando existe decisão humana gravada para pelo
-- menos um dos campos. MARGEM_ALVO e MARGEM_ALVO_VAREJO são NULLABLE e SEM
-- DEFAULT de propósito: NULL significa "sem decisão de margem registrada" e
-- é o dbt (fora desta tabela) que aplica o padrão de negócio de 20%
-- (CONTEXTO.md §6 regra 10). Um DEFAULT 0.20 NOT NULL aqui seria uma mentira
-- silenciosa: um INSERT que só grava preço gravaria margem 0,20 junto, e essa
-- margem ficaria indistinguível de uma decisão humana de fato.
--------------------------------------------------------------------------------
declare
    v_existe number;
begin
    select count(*) into v_existe from user_tables where table_name = 'APP_DECISAO_PRECO';
    if v_existe = 0 then
        execute immediate q'[
            create table app_decisao_preco (
                id_produto           number(10)      not null,
                margem_alvo          number(9,6),
                margem_alvo_varejo   number(9,6),
                alt_pv_at_av         number(14,4),
                alt_pv_var_av        number(14,4),
                atualizado_em        timestamp        default systimestamp not null,
                atualizado_por       varchar2(60)     not null,
                constraint pk_app_decisao_preco primary key (id_produto),
                constraint ck_app_decisao_preco_ma
                    check (margem_alvo between -1 and 1),
                constraint ck_app_decisao_preco_mav
                    check (margem_alvo_varejo between -1 and 1),
                constraint ck_app_decisao_preco_pv
                    check (alt_pv_at_av > 0),
                constraint ck_app_decisao_preco_pvv
                    check (alt_pv_var_av > 0)
            )
        ]';
    end if;
end;
/

comment on table app_decisao_preco is
    'Decisão vigente de margem e preço final por produto. Uma linha por SKU com pelo menos um campo decidido; SKU sem linha, ou com MARGEM_ALVO/MARGEM_ALVO_VAREJO NULL, usa o padrão de negócio (margem 20%) aplicado pelo dbt fora desta tabela. Toda alteração aqui deve gravar o valor anterior em APP_DECISAO_PRECO_HIST antes de sobrescrever.';
comment on column app_decisao_preco.id_produto is
    'CODPROD do CEDEP (cedep.pcprodut.codprod). Não há FK física para CEDEP: a fronteira do projeto proíbe qualquer dependência de schema cruzando para lá (CONTEXTO.md §2).';
comment on column app_decisao_preco.margem_alvo is
    'Margem alvo decidida para o atacado, fração decimal (0.20 = 20%; CHECK entre -1 e 1 — quem digitar "20" achando que é 20% recebe erro em vez de gravar 2000%). NULL = sem decisão humana registrada; o padrão de 20% (CONTEXTO.md §6 regra 10) é aplicado pelo dbt fora desta tabela, nunca gravado aqui como default.';
comment on column app_decisao_preco.margem_alvo_varejo is
    'Margem alvo decidida para o varejo (filiais fora de 02/09), fração decimal, mesma semântica de NULL e mesmo CHECK entre -1 e 1 de MARGEM_ALVO.';
comment on column app_decisao_preco.alt_pv_at_av is
    'Preço de venda final decidido para o atacado (ALT_PV_AT_AV). CHECK > 0 quando não nulo. NULL = ainda sem decisão humana registrada para este campo; nunca é preenchido automaticamente com uma sugestão do modelo (CONTEXTO.md §6 regra 10).';
comment on column app_decisao_preco.alt_pv_var_av is
    'Preço de venda final decidido para o varejo (ALT_PV_VAR_AV). CHECK > 0 quando não nulo. Mesma semântica de NULL que ALT_PV_AT_AV.';
comment on column app_decisao_preco.atualizado_em is
    'Timestamp da última gravação desta linha (não da criação).';
comment on column app_decisao_preco.atualizado_por is
    'Login (APP_USUARIO.login) de quem gravou o valor vigente.';

--------------------------------------------------------------------------------
-- 2. APP_DECISAO_PRECO_HIST — todo valor anterior de APP_DECISAO_PRECO.
--
-- Antes de sobrescrever uma linha em APP_DECISAO_PRECO, a aplicação grava o
-- valor que está saindo aqui. DECIDIDO_EM é o instante desse arquivamento
-- (quando o valor deixou de valer), não o instante em que ele foi criado —
-- esse já está em ATUALIZADO_EM, copiado da linha original. MARGEM_ALVO e
-- MARGEM_ALVO_VAREJO são NULLABLE aqui pela mesma razão que em
-- APP_DECISAO_PRECO: uma linha arquivada pode ter sido gravada só com preço,
-- sem margem decidida, e o histórico precisa preservar esse NULL, não
-- inventar um valor.
--------------------------------------------------------------------------------
declare
    v_existe number;
begin
    select count(*) into v_existe from user_tables where table_name = 'APP_DECISAO_PRECO_HIST';
    if v_existe = 0 then
        execute immediate q'[
            create table app_decisao_preco_hist (
                id_hist              number         generated always as identity,
                id_produto           number(10)      not null,
                margem_alvo          number(9,6),
                margem_alvo_varejo   number(9,6),
                alt_pv_at_av         number(14,4),
                alt_pv_var_av        number(14,4),
                atualizado_em        timestamp        not null,
                atualizado_por       varchar2(60)     not null,
                decidido_em          timestamp        default systimestamp not null,
                constraint pk_app_decisao_preco_hist primary key (id_hist),
                constraint ck_app_decisao_preco_h_ma
                    check (margem_alvo between -1 and 1),
                constraint ck_app_decisao_preco_h_mav
                    check (margem_alvo_varejo between -1 and 1),
                constraint ck_app_decisao_preco_h_pv
                    check (alt_pv_at_av > 0),
                constraint ck_app_decisao_preco_h_pvv
                    check (alt_pv_var_av > 0)
            )
        ]';
    end if;
end;
/

declare
    v_existe number;
begin
    select count(*) into v_existe from user_indexes where index_name = 'IX_APP_DECISAO_PRECO_HIST_PRD';
    if v_existe = 0 then
        execute immediate
            'create index ix_app_decisao_preco_hist_prd on app_decisao_preco_hist (id_produto)';
    end if;
end;
/

comment on table app_decisao_preco_hist is
    'Histórico de todo valor anterior de APP_DECISAO_PRECO. Uma linha é inserida aqui a cada vez que uma linha de APP_DECISAO_PRECO é sobrescrita, com o conteúdo que estava saindo. Nunca é alterada nem apagada pela aplicação — só cresce.';
comment on column app_decisao_preco_hist.id_hist is
    'Chave técnica sequencial (IDENTITY, GENERATED ALWAYS — nunca aceita id explícito em uso normal), sem significado de negócio.';
comment on column app_decisao_preco_hist.id_produto is
    'CODPROD do CEDEP a que este valor histórico se refere. Indexado (IX_APP_DECISAO_PRECO_HIST_PRD) para consultar o histórico de um produto.';
comment on column app_decisao_preco_hist.margem_alvo is
    'Margem alvo do atacado que estava vigente antes desta substituição. NULL = a linha arquivada não tinha margem de atacado decidida (mesma semântica de APP_DECISAO_PRECO.margem_alvo). CHECK entre -1 e 1.';
comment on column app_decisao_preco_hist.margem_alvo_varejo is
    'Margem alvo do varejo que estava vigente antes desta substituição. NULL = a linha arquivada não tinha margem de varejo decidida. CHECK entre -1 e 1.';
comment on column app_decisao_preco_hist.alt_pv_at_av is
    'Preço final de atacado que estava vigente antes desta substituição (pode ser NULL, mesma semântica de APP_DECISAO_PRECO.alt_pv_at_av). CHECK > 0 quando não nulo.';
comment on column app_decisao_preco_hist.alt_pv_var_av is
    'Preço final de varejo que estava vigente antes desta substituição (pode ser NULL). CHECK > 0 quando não nulo.';
comment on column app_decisao_preco_hist.atualizado_em is
    'ATUALIZADO_EM original, copiado da linha de APP_DECISAO_PRECO no momento em que ela foi substituída — quando aquele valor passou a valer, não quando foi arquivado.';
comment on column app_decisao_preco_hist.atualizado_por is
    'ATUALIZADO_POR original, copiado da linha de APP_DECISAO_PRECO no momento da substituição.';
comment on column app_decisao_preco_hist.decidido_em is
    'Instante em que este valor deixou de ser o vigente (foi arquivado aqui por uma nova decisão).';
